[project]
name = "agenticai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Mohith824", email = "mohith072005@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "openai>=3.10.0",
    "pygame>=2.5.0",
    "python-dotenv>=1.2.3",
]

[project.scripts]
agenticai = "agenticai:main"

[build-system]
requires = ["uv_build>=0.12.11,<0.13.0"]
build-backend = "uv_build"
